version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
       - ./:/app
       - /app/nodde_modules
    environment:
       - NODE_ENV=development
    command: npm start
     