version: "3"
services:
  node-app:
   build: .
   ports:
     - "3001:3001"
   environment:
     - PORT=3001
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harshad
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:

